# Generated by Django 5.1.3 on 2024-11-23 00:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CathegoryRecipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('FIRST_COURSES', 'First courses'), ('SECOND', 'Second courses'), ('SNACKS', 'Snacks'), ('SALADS', 'Salads')], max_length=50, verbose_name='Название категории')),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Заголовок рецепта')),
                ('description', models.TextField(verbose_name='Описание рецепта')),
                ('cooking_steps', models.TextField(verbose_name='Шаги приготовления')),
                ('cooking_time', models.DurationField(verbose_name='Время приготовления (чч:мм:сс)')),
                ('active', models.BooleanField(default=True, verbose_name='Статус активности')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор рецепта')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipapp.cathegoryrecipe', verbose_name='Категория')),
            ],
        ),
    ]
