# Generated by Django 5.1.3 on 2024-11-23 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='active',
        ),
        migrations.AlterField(
            model_name='cathegoryrecipe',
            name='name',
            field=models.CharField(choices=[('FC', 'First courses'), ('SC', 'Second courses'), ('SN', 'Snacks'), ('SA', 'Salads')], max_length=100, verbose_name='Название категории'),
        ),
    ]
