# Generated by Django 5.1.3 on 2024-11-23 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipapp', '0002_remove_recipe_active_alter_cathegoryrecipe_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cathegoryrecipe',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название категории'),
        ),
    ]
